TARGET := picosoc_system

C_SRCS := \
	picosoc_system.c \

HEADERS := \
#     defs.h \
# 	utilities.h \
#     cephes.h \

CFLAGS := -O3 -fno-builtin-printf -ffunction-sections -nostdlib

BSP_BASE = ../../

include $(BSP_BASE)/common.mk
