TARGET := aes

C_SRCS := \
	aes.c test.c \

HEADERS := \
	aes.h
#     defs.h \
# 	utilities.h \
#     cephes.h \

CFLAGS := -O3 -fno-builtin-printf -ffunction-sections -nostdlib

BSP_BASE = ../../

include $(BSP_BASE)/common.mk
